### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by joaopedro5g** [yvesvanbelle/BSI#1]
You have BSI documentation in PDF?

**Comment by hasechris** [comment]
I came here to second this @yvesvanbelle. Do you have any information regarding the needed xml language?

**Comment by yvesvanbelle** [comment]
Hello Chrtistian,

You can get th BSI documentation free of cost from your local Brother office. That is I obtained the doc. They only inform why you need the doc.

Best regards,

Yves
________________________________
Van: Christian Hase ***@***.***>
Verzonden: zondag 21 januari 2024 5:26
Aan: yvesvanbelle/BSI ***@***.***>
CC: Yves Van Belle ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [yvesvanbelle/BSI] Documentation (Issue #1)


I came here to second this @yvesvanbelle<https://github.com/yvesvanbelle>. Do you have any information regarding the needed xml language?
